version: "3.9"
services: 
  client-image:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    container_name: client-dc
    restart: unless-stopped
    ports:
      - 3001:3000
    volumes:
      - ./client:/usr/src
    environment:
      HOST: 0.0.0.0
      # - CHOKIDAR_USEPOLLING=true
      
  # server-image:
  #   build:
  #     context: ./server
  #     dockerfile: Dockerfile
  #   container_name: server-dc
  #   ports:
  #     - 8080:8080
  #   volumes:
  #     - './server:/usr/app'
  #   environment:
  #     - CHOKIDAR_USEPOLLING=true